### Working with strings

The string medical_data stores the medical records for ten individuals. Each record is separated by a ; and contains the name, age, BMI (body mass index), and insurance cost for an individual, in that order.

We want the insurance costs to be represented in US dollars. Replace all instances of # in medical_data with $. Store the result in a variable called updated_medical_data.
Print updated_medical_data.

In [16]:
medical_data = \
"""Marina Allison   ,27   ,   31.1 , 
#7010.0   ;Markus Valdez   ,   30, 
22.4,   #4050.0 ;Connie Ballard ,43 
,   25.3 , #12060.0 ;Darnell Weber   
,   35   , 20.6   , #7500.0;
Sylvie Charles   ,22, 22.1 
,#3022.0   ;   Vinay Padilla,24,   
26.9 ,#4620.0 ;Meredith Santiago, 51   , 
29.3 ,#16330.0;   Andre Mccarty, 
19,22.7 , #2900.0 ; 
Lorena Hodson ,65, 33.1 , #19370.0; 
Isaac Vu ,34, 24.8,   #7045.0"""

# Add your code here
updated_medical_data = medical_data.replace("#", "$")
print(updated_medical_data)

Marina Allison   ,27   ,   31.1 , 
$7010.0   ;Markus Valdez   ,   30, 
22.4,   $4050.0 ;Connie Ballard ,43 
,   25.3 , $12060.0 ;Darnell Weber   
,   35   , 20.6   , $7500.0;
Sylvie Charles   ,22, 22.1 
,$3022.0   ;   Vinay Padilla,24,   
26.9 ,$4620.0 ;Meredith Santiago, 51   , 
29.3 ,$16330.0;   Andre Mccarty, 
19,22.7 , $2900.0 ; 
Lorena Hodson ,65, 33.1 , $19370.0; 
Isaac Vu ,34, 24.8,   $7045.0


We want to calculate the number of medical records in our data. Create a variable called num_records and initialize it at 0.

Next, write a for loop to iterate through the updated_medical_data string. Inside of the loop, add 1 to num_records when the current character is equal to $.

Outside of the loop, print num_records with the following message:
"There are {num_records} medical records in the data."

In [17]:
num_records = 0
for char in updated_medical_data:
  if char == "$":
    num_records += 1
print("There are {} medical records in the data".format(num_records))

There are 10 medical records in the data


### Splitting strings

The medical data in its current form is difficult to analyze. An essential job for a data scientist is to clean up data so that it’s easy to work with.
Let’s start off by splitting the updated_medical_data string into a list of each medical record. Remember that each medical record is separated by a ; in the string.
Store the result in a variable called medical_data_split

In [18]:
medical_data_split = updated_medical_data.split(";")
print(medical_data_split)

['Marina Allison   ,27   ,   31.1 , \n$7010.0   ', 'Markus Valdez   ,   30, \n22.4,   $4050.0 ', 'Connie Ballard ,43 \n,   25.3 , $12060.0 ', 'Darnell Weber   \n,   35   , 20.6   , $7500.0', '\nSylvie Charles   ,22, 22.1 \n,$3022.0   ', '   Vinay Padilla,24,   \n26.9 ,$4620.0 ', 'Meredith Santiago, 51   , \n29.3 ,$16330.0', '   Andre Mccarty, \n19,22.7 , $2900.0 ', ' \nLorena Hodson ,65, 33.1 , $19370.0', ' \nIsaac Vu ,34, 24.8,   $7045.0']


Our data is now stored in a list, but it is still hard to read. Let’s split each medical record into its own list.
First, define an empty list called medical_records.

Next, iterate through medical_data_split and for each record, split the string after each comma (,) and append the split string to medical_records.
Print medical_records after the loop.

In [19]:
medical_data_split = updated_medical_data.split(";")
medical_records = []
for records in medical_data_split:
  medical_records.append(records.split(","))
print(medical_records)

[['Marina Allison   ', '27   ', '   31.1 ', ' \n$7010.0   '], ['Markus Valdez   ', '   30', ' \n22.4', '   $4050.0 '], ['Connie Ballard ', '43 \n', '   25.3 ', ' $12060.0 '], ['Darnell Weber   \n', '   35   ', ' 20.6   ', ' $7500.0'], ['\nSylvie Charles   ', '22', ' 22.1 \n', '$3022.0   '], ['   Vinay Padilla', '24', '   \n26.9 ', '$4620.0 '], ['Meredith Santiago', ' 51   ', ' \n29.3 ', '$16330.0'], ['   Andre Mccarty', ' \n19', '22.7 ', ' $2900.0 '], [' \nLorena Hodson ', '65', ' 33.1 ', ' $19370.0'], [' \nIsaac Vu ', '34', ' 24.8', '   $7045.0']]


### Cleaning data

Our data is now slightly more readable. However, it is not properly formatted – it contains unnecessary whitespace.
To fix this, let’s start by creating an empty list called medical_records_clean.

Next, use a for loop to iterate through medical_records. Inside of the loop, create an empty list called record_clean. We’ll use this list to store a formatted version of each medical record.

After the record_clean variable, create a nested for loop that goes through each record:
"for item in record:"
Inside of this loop, append item.strip() to record_clean to remove any whitespace from the string.

Finally, we need to add each cleaned up record to medical_records_clean. Outside of the nested for loop, append record_clean to medical_records_clean.

In [20]:
medical_records_clean = []
for record in medical_records:
  record_clean = []
  for data in record:
    record_clean.append(data.strip())
  medical_records_clean.append(record_clean)
print(medical_records_clean)

[['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Meredith Santiago', '51', '29.3', '$16330.0'], ['Andre Mccarty', '19', '22.7', '$2900.0'], ['Lorena Hodson', '65', '33.1', '$19370.0'], ['Isaac Vu', '34', '24.8', '$7045.0']]


### Analyzing data

Our data is now clean and ready for analysis.
For example, to print out the names of each of the ten individuals, we can use the following loop:

"for record in medical_records_clean:  
  print(record[0])"
  
Add this loop to your code and click “Save.”

In [21]:
for record in medical_records_clean:
  print(record[0])

Marina Allison
Markus Valdez
Connie Ballard
Darnell Weber
Sylvie Charles
Vinay Padilla
Meredith Santiago
Andre Mccarty
Lorena Hodson
Isaac Vu


You want all of the names in the medical records to be in uppercase characters.
In the for loop, update records[0] before the print statement so that all of the characters are uppercase.

In [22]:
for record in medical_records_clean:
    record[0] = record[0].upper()
    print(record[0])

MARINA ALLISON
MARKUS VALDEZ
CONNIE BALLARD
DARNELL WEBER
SYLVIE CHARLES
VINAY PADILLA
MEREDITH SANTIAGO
ANDRE MCCARTY
LORENA HODSON
ISAAC VU


Let’s store each name, age, BMI, and insurance cost in separate lists.
To start, create four empty lists:
- names
- ages
- bmis
- insurance_costs

Next, iterate through medical_records_clean and for each record:
- Append the name to names.
- Append the age to ages.
- Append the BMI to bmis.
- Append the insurance cost to insurance_costs.

Print names, ages, bmis, and insurance_costs outside of the loop.

In [23]:
names = []
ages = []
bmis = []
insurance_costs = []
for record in medical_records_clean:
  names.append(record[0])
  ages.append(record[1])
  bmis.append(record[2])
  insurance_costs.append(record[3])

print(names)
print(ages)
print(bmis)
print(insurance_costs)

['MARINA ALLISON', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'DARNELL WEBER', 'SYLVIE CHARLES', 'VINAY PADILLA', 'MEREDITH SANTIAGO', 'ANDRE MCCARTY', 'LORENA HODSON', 'ISAAC VU']
['27', '30', '43', '35', '22', '24', '51', '19', '65', '34']
['31.1', '22.4', '25.3', '20.6', '22.1', '26.9', '29.3', '22.7', '33.1', '24.8']
['$7010.0', '$4050.0', '$12060.0', '$7500.0', '$3022.0', '$4620.0', '$16330.0', '$2900.0', '$19370.0', '$7045.0']


Now that all of our data is in separate lists, we can easily perform analysis on that data. Let’s calculate the average BMI in our dataset.
First, create a variable called total_bmi and set it equal to 0.

Next, use a for loop to iterate through bmis and add each bmi to total_bmi.
Remember to convert bmi to a float.

After the for loop, create a variable called average_bmi that stores the total_bmi divided by the length of the bmis list. Print out average_bmi with the following message:
"Average BMI: {average_bmi}"

In [24]:
total_bmi = 0
for bmi in bmis:
  total_bmi += float(bmi)
average_bmi = total_bmi / len(bmis)
print("Average BMI: " + str(average_bmi))

Average BMI: 25.830000000000002


### Extra

Write a for loop that outputs a string for each individual in the following format:

"Marina is 27 year olds with a BMI of 31.1 and an insurance cost of $7010.0.

Markus is 30 years old with a BMI of 22.4 and an insurance cost of $4050.0

...

..."

In [26]:
for records in medical_records_clean:
  print("{} is {} years old with a BMI of {} and an insurance cost of {}".format(records[0].title(), records[1], records[2], records[3]))

Marina Allison is 27 years old with a BMI of 31.1 and an insurance cost of $7010.0
Markus Valdez is 30 years old with a BMI of 22.4 and an insurance cost of $4050.0
Connie Ballard is 43 years old with a BMI of 25.3 and an insurance cost of $12060.0
Darnell Weber is 35 years old with a BMI of 20.6 and an insurance cost of $7500.0
Sylvie Charles is 22 years old with a BMI of 22.1 and an insurance cost of $3022.0
Vinay Padilla is 24 years old with a BMI of 26.9 and an insurance cost of $4620.0
Meredith Santiago is 51 years old with a BMI of 29.3 and an insurance cost of $16330.0
Andre Mccarty is 19 years old with a BMI of 22.7 and an insurance cost of $2900.0
Lorena Hodson is 65 years old with a BMI of 33.1 and an insurance cost of $19370.0
Isaac Vu is 34 years old with a BMI of 24.8 and an insurance cost of $7045.0
